### PR TITLE
fix #1 - added explicit dependency to libc to avoid `cargo build` error

### LINKED ISSUE #1: libc error when building
mod_prometheus build fails with this message:

```
$ cargo build
[...]
   Compiling mod_prometheus v0.1.0 (file:///usr/local/src/freeswitch/src/mod/applications/mod_prometheus)
mod_prometheus.rs:22:1: 22:19 error: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)
mod_prometheus.rs:22 extern crate libc;
                     ^~~~~~~~~~~~~~~~~~
<freeswitchrs macros>:10:24: 10:38 error: use of unstable library feature 'libc': use `libc` from crates.io (see issue #27783)
<freeswitchrs macros>:10 as_ptr (  ) as * const libc :: c_char , line ! (  ) as libc :: c_int , $ level
[...]
```

Versions:
mod_prometheus 91f2615de61
rustc 1.11.0 (9b21dcd6a 2016-08-15)

### PR DESCRIPTION
**Pull request by hdiogenes**
Don't know if this is the Right Solution™, but it worked for me.

### CODE REVIEW

**Comment by moises-silva** [comment]
@hdiogenes It is the right solution but the version specified is old, you should put `libc = "*"` as we're fine with any libc crate version really (and there's much newer versions available). In fact, I have that change in my local repo but I did not commit it weeks ago 😢 

Please rebase your commit with the right version specifier (the wildcard) and I'll merge it

**Comment by hdiogenes** [comment]
Nice, @moises-silva! I tested with '*' and it worked. PR updated.

**Comment by moises-silva** [comment]
@hdiogenes I squashed your commit and reworded it, so I'm closing this PR but your changes are in master already. Thanks! In the future you can use `git rebase` yourself. You can also take inspiration on how to format your commit messages from here: http://chris.beams.io/posts/git-commit/

**Comment by hdiogenes** [comment]
Thanks, @moises-silva!

**Pull request closed without merging**
